application:
  name: @project.name@
  version: @project.version@
  token:
    durationInMilliseconds: 300_000
    key: "txp2wk99k6UKGM9Lr+DX29v0lntp9RTwQUiv+ZzOYoA="
    header: "Authorization"
    prefix: "Bearer"
    claimsName: "license"

server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: @project.profile@

---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: "GMT-03:00"
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

---

spring:
  profiles: test
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: "GMT-03:00"

debug: true
